---
- name: Install NTP server
  yum: name=chrony state=installed
  when: ansible_os_family == "RedHat"

- name: Configure controller node NTP server
  template: src=chrony.conf.server.j2 dest=/etc/chrony.conf owner=root group=root mode=0644
  when: ansible_fqdn == "controller"
  notify:
    - restart NTP server

- name: Configure other node NTP client
  template: src=chrony.conf.client.j2 dest=/etc/chrony.conf owner=root group=root mode=0644
  when: not ansible_fqdn == "controller"
  notify:
    - restart NTP server

- name: NTP server now is running
  service: name=chronyd.service enabled=yes state=started
